name: Unity ApiCaller CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test-runner:
    name: ${{ matrix.testMode }} Tests
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - PlayMode
          - EditMode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Cache library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.testMode }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.testMode }}-
            Library-

      - name: Run tests
        id: tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ github.workspace }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Tests Result

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.testMode }} Tests Result
          path: ${{ steps.tests.outputs.artifactsPath }}